app <- ShinyDriver$new("../../", shinyOptions = list(test.mode = TRUE))
.thistest <- "convertchain"
app$snapshotInit(.thistest)

# cannot test writing of xlsx,spss because apparently they store timestamps
message('\nreading xls format')
app$snapshot()
app$uploadFile(infile = "iris.xls")
app$snapshot()
app$setInputs(import = "click")
app$snapshot()
app$setInputs(saveas = "rda")
app$snapshot()
app$setInputs(convert = "click")
app$snapshot()
app$snapshotDownload("download")
message('reading rda format')
message
app$uploadFile(infile = file.path(paste0(.thistest,"-current"),"006.download"))
app$snapshot()
app$setInputs(import = "click")
app$snapshot()
app$setInputs(saveas = "csv")
app$snapshot()
app$setInputs(convert = "click")
app$snapshot()
app$snapshotDownload("download")
message('reading csv format')
app$uploadFile(infile = file.path(paste0(.thistest,"-current"),"011.download"))
app$snapshot()
app$setInputs(import = "click")
app$snapshot()
app$setInputs(saveas = "xml")
app$snapshot()
app$setInputs(convert = "click")
app$snapshot()
app$snapshotDownload("download")
message('reading xml format')
app$uploadFile(infile = file.path(paste0(.thistest,"-current"),"016.download"))
app$snapshot()
app$setInputs(import = "click")
app$snapshot()
app$setInputs(saveas = "html")
app$snapshot()
app$setInputs(convert = "click")
app$snapshot()
app$snapshotDownload("download")
message('reading html format')
app$uploadFile(infile = file.path(paste0(.thistest,"-current"),"021.download"))
app$snapshot()
app$setInputs(import = "click")
app$snapshot()
app$setInputs(saveas = "json",timeout_=10000)
app$snapshot()
app$setInputs(convert = "click")
app$snapshot()
app$snapshotDownload("download")
message('reading json format')
app$uploadFile(infile = file.path(paste0(.thistest,"-current"),"026.download"))
app$snapshot()
app$setInputs(import = "click")
app$snapshot()
app$setInputs(saveas = "yml")
app$snapshot()
app$setInputs(convert = "click")
app$snapshot()
app$snapshotDownload("download")


widgets <- app$listWidgets()
dump('widgets',file = file.path(paste0(.thistest,"-current"),"widgets.dump"))

